controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    legs_position_controller:
      type: position_controllers/JointGroupPositionController

legs_position_controller:
  ros__parameters:
    joints:
      - FR_root_joint
      - FR_hip_joint
      - FR_knee_joint
      - FL_root_joint
      - FL_hip_joint
      - FL_knee_joint
      - RR_root_joint
      - RR_hip_joint
      - RR_knee_joint
      - RL_root_joint
      - RL_hip_joint
      - RL_knee_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

